"""Tests for AI-Assisted PR Rate metric."""

import pytest
from datetime import datetime, timezone
from unittest.mock import MagicMock

from impact.domain.models import MetricContext
from impact.metrics.plugins.authored.ai_assisted_pr_rate import (
    AIAssistedPRRate,
    _detect_ai_assistance,
)


class TestDetectAIAssistance:
    """Test the _detect_ai_assistance helper function."""

    def test_detects_copilot_in_commit_message(self):
        text = "Add feature\n\nCo-authored-by: GitHub Copilot"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "copilot"

    def test_detects_cursor_in_title(self):
        text = "Fix bug (generated by Cursor)"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "cursor"

    def test_detects_claude_in_body(self):
        text = "This PR was generated with Claude Code assistance"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "claude"

    def test_detects_chatgpt(self):
        text = "Refactor function - generated by ChatGPT"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "chatgpt"

    def test_detects_generic_ai_generated(self):
        text = "Update docs (AI generated)"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "ai_assisted"

    def test_no_false_positives_for_normal_text(self):
        text = "This is a normal PR description about cursor movement"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is False
        assert tool is None

    def test_handles_none_text(self):
        is_ai, tool = _detect_ai_assistance(None)
        assert is_ai is False
        assert tool is None

    def test_handles_empty_text(self):
        is_ai, tool = _detect_ai_assistance("")
        assert is_ai is False
        assert tool is None

    def test_detects_cody(self):
        text = "Fix using Cody by Sourcegraph"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "cody"

    def test_detects_tabnine(self):
        text = "Completion via Tabnine"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "tabnine"


def make_mock_pr(number: int, title: str, body: str = "", user_login: str = "testuser"):
    """Create a mock PR with all required attributes for filter_prs_for_contribution."""
    pr = MagicMock()
    pr.number = number
    pr.title = title
    pr.body = body
    pr.draft = False
    pr.merged = True
    pr.created_at = datetime(2024, 1, 15, tzinfo=timezone.utc)
    
    # Nested user mock
    user_mock = MagicMock()
    user_mock.login = user_login
    pr.user = user_mock
    
    return pr


def make_mock_commit(sha: str, message: str, user_login: str = "testuser"):
    """Create a mock commit with minimal required attributes."""
    commit = MagicMock()
    commit.sha = sha
    commit.message = message
    commit.date = datetime(2024, 1, 15, tzinfo=timezone.utc)
    
    # Nested author mock
    author_mock = MagicMock()
    author_mock.login = user_login
    commit.author = author_mock
    
    return commit


class TestAIAssistedPRRateMetric:
    """Test the AIAssistedPRRate metric class."""

    @pytest.fixture
    def metric(self):
        return AIAssistedPRRate()

    @pytest.fixture
    def mock_context(self):
        """Create a mock context with test PRs."""
        context = MagicMock(spec=MetricContext)
        context.user_login = "testuser"
        context.start_date = datetime(2024, 1, 1, tzinfo=timezone.utc)
        context.end_date = datetime(2024, 1, 31, tzinfo=timezone.utc)

        # Mock ledger
        ledger = MagicMock()
        context.ledger = ledger

        return context, ledger

    def test_metric_properties(self, metric):
        assert metric.slug == "ai_assisted_pr_rate"
        assert metric.name == "AI-Assisted PR Rate"
        assert metric.category == "contextual"
        assert "DevRank" in metric.frameworks

    def test_no_prs_returns_no_data(self, metric, mock_context):
        context, ledger = mock_context
        ledger.get_prs_for_user.return_value = []

        result = metric.run(context)

        assert result.metric_slug == "ai_assisted_pr_rate"
        assert result.details["total_pr_count"] == 0
        assert result.details["no_data"] is True
        assert "No PRs found" in result.summary

    def test_all_human_prs(self, metric, mock_context):
        context, ledger = mock_context

        # Create human PRs
        prs = [
            make_mock_pr(1, "Fix bug", "Manual fix"),
            make_mock_pr(2, "Add feature", "Implemented manually"),
        ]
        ledger.get_prs_for_user.return_value = prs
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        assert result.details["ai_rate"] == 0.0
        assert result.details["ai_pr_count"] == 0
        assert result.details["human_pr_count"] == 2
        assert result.details["total_pr_count"] == 2
        assert "0.0% AI-assisted" in result.summary

    def test_mixed_ai_and_human_prs(self, metric, mock_context):
        context, ledger = mock_context

        # Create mixed PRs
        human_pr = make_mock_pr(1, "Fix bug", "Manual fix")
        ai_pr = make_mock_pr(2, "Add feature (generated by Copilot)", "AI assisted implementation")
        prs = [human_pr, ai_pr]
        ledger.get_prs_for_user.return_value = prs
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        assert result.details["ai_rate"] == 50.0
        assert result.details["ai_pr_count"] == 1
        assert result.details["human_pr_count"] == 1
        assert "50.0% AI-assisted" in result.summary
        assert "copilot" in str(result.details["tool_breakdown"]).lower()

    def test_detects_ai_in_commit_messages(self, metric, mock_context):
        context, ledger = mock_context

        pr = make_mock_pr(1, "Update feature", "Some changes")
        ledger.get_prs_for_user.return_value = [pr]

        # AI detected in commit message
        ai_commit = make_mock_commit("abc123", "Add function\n\nGenerated by Claude Code")
        ledger.get_commits_for_pr.return_value = [ai_commit]

        result = metric.run(context)

        assert result.details["ai_rate"] == 100.0
        assert result.details["ai_pr_count"] == 1
        assert "claude" in str(result.details["tool_breakdown"]).lower()

    def test_tool_breakdown_aggregation(self, metric, mock_context):
        context, ledger = mock_context

        # Multiple PRs with different AI tools
        prs = [
            make_mock_pr(1, "Fix (Copilot)"),
            make_mock_pr(2, "Feature (Cursor)"),
            make_mock_pr(3, "Another (Copilot)"),
        ]
        ledger.get_prs_for_user.return_value = prs
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        breakdown = result.details["tool_breakdown"]
        assert breakdown["copilot"] == 2
        assert breakdown["cursor"] == 1

    def test_no_data_guard_short_period_low_count(self, metric, mock_context):
        context, ledger = mock_context
        context.start_date = datetime(2024, 1, 1, tzinfo=timezone.utc)
        context.end_date = datetime(2024, 1, 5, tzinfo=timezone.utc)  # Only 4 days

        # Only 2 PRs in short period
        prs = [
            make_mock_pr(1, "PR 1"),
            make_mock_pr(2, "PR 2"),
        ]
        ledger.get_prs_for_user.return_value = prs
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        # Should mark as no_data due to short period + low count
        assert result.details["no_data"] is True

    def test_sufficient_data_longer_period(self, metric, mock_context):
        context, ledger = mock_context
        # 20 days period with 2 PRs
        context.start_date = datetime(2024, 1, 1, tzinfo=timezone.utc)
        context.end_date = datetime(2024, 1, 21, tzinfo=timezone.utc)

        prs = [
            make_mock_pr(1, "PR 1"),
            make_mock_pr(2, "PR 2"),
        ]
        ledger.get_prs_for_user.return_value = prs
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        # Should NOT mark as no_data - longer period makes it valid
        assert result.details.get("no_data") is not True
        assert result.details["total_pr_count"] == 2

    def test_per_pr_evidence_structure(self, metric, mock_context):
        context, ledger = mock_context

        pr = make_mock_pr(1, "Feature by Copilot", "Generated with AI")
        ledger.get_prs_for_user.return_value = [pr]
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        per_pr = result.details["per_pr"]
        assert len(per_pr) == 1
        assert per_pr[0]["number"] == 1
        assert per_pr[0]["is_ai_assisted"] is True
        assert per_pr[0]["tool"] == "copilot"
        assert "evidence" in per_pr[0]
        # Evidence should contain source info
        assert any(e.get("source") in ["pr_title", "pr_body"] for e in per_pr[0]["evidence"])
