"""Tests for static analysis utilities (Phases 1-2: generated files, hunk parsing, test detection, structural diff, code-aware comments)."""
import math
from datetime import timedelta

from impact.metrics.plugins.authored.pr_size_distribution import PRSizeDistribution
from impact.metrics.plugins.authored.trivial_contribution_rate import TrivialContributionRate
from impact.metrics.utils import (
    _compression_ratio,
    _parse_hunk_lines,
    _shannon_entropy,
    analyze_file_complexity,
    build_module_map,
    classify_diff_structure,
    compute_trivial_ratio,
    detect_module_boundary,
    extract_code_blocks,
    get_pr_effective_changes,
    is_conventional_commit,
    is_dependency_file,
    is_documentation_file,
    is_generated_file,
    is_test_content,
    is_test_file_or_content,
    parse_functions,
    parse_hunks,
    score_code_block_quality,
    score_comment_code_quality,
)
from impact.tests.conftest import (
    DEFAULT_START,
    make_bundle,
    make_context,
    make_file,
    make_pr,
    make_repo,
    make_user,
)


# ---------------------------------------------------------------------------
# is_generated_file — filename patterns
# ---------------------------------------------------------------------------

class TestIsGeneratedFileByName:
    def test_lockfiles(self):
        assert is_generated_file("package-lock.json")
        assert is_generated_file("yarn.lock")
        assert is_generated_file("poetry.lock")
        assert is_generated_file("Cargo.lock")  # case-insensitive
        assert is_generated_file("go.sum")

    def test_minified(self):
        assert is_generated_file("app.min.js")
        assert is_generated_file("styles.min.css")
        assert is_generated_file("vendor.bundle.js")

    def test_protobuf(self):
        assert is_generated_file("api.pb.go")
        assert is_generated_file("service.pb.py")
        assert is_generated_file("types.pb.cc")

    def test_snapshots(self):
        assert is_generated_file("Component.test.tsx.snap")
        assert is_generated_file("__snapshots__/foo.snap")

    def test_vendor_dirs(self):
        assert is_generated_file("vendor/github.com/pkg/errors/errors.go")
        assert is_generated_file("node_modules/lodash/index.js")
        assert is_generated_file("dist/bundle.js")

    def test_migrations(self):
        assert is_generated_file("migrations/0001_initial.py")
        assert is_generated_file("db/migrations/20230101_create_users.sql")

    def test_generated_dirs(self):
        assert is_generated_file("__generated__/schema.ts")
        assert is_generated_file("src/generated/types.go")

    def test_normal_source_not_generated(self):
        assert not is_generated_file("src/main.py")
        assert not is_generated_file("lib/utils.ts")
        assert not is_generated_file("package.json")  # not lock
        assert not is_generated_file("README.md")
        assert not is_generated_file("tests/test_foo.py")

    def test_svg_detected(self):
        assert is_generated_file("logo.svg")
        assert is_generated_file("icons/arrow.svg")

    def test_empty_filename(self):
        assert not is_generated_file("")
        assert not is_generated_file(None)  # type: ignore


# ---------------------------------------------------------------------------
# is_generated_file — patch content analysis
# ---------------------------------------------------------------------------

class TestIsGeneratedFileByPatch:
    def test_generated_marker_in_header(self):
        patch = (
            "@@ -0,0 +1,5 @@\n"
            "+// Code generated by protoc-gen-go. DO NOT EDIT.\n"
            "+package api\n"
            "+\n"
            "+type Foo struct{}\n"
        )
        assert is_generated_file("api/types.go", patch)

    def test_auto_generated_marker(self):
        patch = (
            "@@ -0,0 +1,3 @@\n"
            "+# This file is auto-generated\n"
            "+CONFIG = {}\n"
        )
        assert is_generated_file("config.py", patch)

    def test_at_generated_marker(self):
        patch = (
            "@@ -0,0 +1,3 @@\n"
            "+/* @generated */\n"
            "+export const x = 1;\n"
        )
        assert is_generated_file("output.js", patch)

    def test_normal_patch_not_generated(self):
        patch = (
            "@@ -1,3 +1,5 @@\n"
            " def hello():\n"
            "-    print('hello')\n"
            "+    print('hello world')\n"
            "+    return True\n"
        )
        assert not is_generated_file("src/hello.py", patch)

    def test_minified_content_high_entropy(self):
        # Simulate minified JS: long line, high entropy, hard to compress
        import random
        random.seed(42)
        chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789(){}[];:,.'\"!@#$%^&*"
        minified = "".join(random.choice(chars) for _ in range(2000))
        patch = "@@ -0,0 +1,1 @@\n+" + minified
        assert is_generated_file("app.js", patch)

    def test_repetitive_generated_code(self):
        # Extremely repetitive machine-generated code (very low compression ratio)
        line = "+    this.field_{i} = value_{i};\n"
        lines = [f"+    this.field_{i} = value_{i};" for i in range(200)]
        patch = "@@ -0,0 +1,200 @@\n" + "\n".join(lines)
        # This should have extremely low compression ratio
        result = is_generated_file("generated_model.java", patch)
        # May or may not trigger depending on exact entropy/ratio — just ensure no crash
        assert isinstance(result, bool)


# ---------------------------------------------------------------------------
# Shannon entropy helper
# ---------------------------------------------------------------------------

class TestShannonEntropy:
    def test_empty(self):
        assert _shannon_entropy(b"") == 0.0

    def test_single_byte(self):
        assert _shannon_entropy(b"aaaa") == 0.0  # no variance

    def test_uniform_distribution(self):
        # 256 distinct bytes: max entropy = 8 bits
        data = bytes(range(256))
        entropy = _shannon_entropy(data)
        assert abs(entropy - 8.0) < 0.01

    def test_low_entropy_text(self):
        data = b"aaabbbccc"
        entropy = _shannon_entropy(data)
        assert entropy < 2.0  # very low

    def test_code_like_entropy(self):
        data = b"def hello():\n    print('hello world')\n    return True\n"
        entropy = _shannon_entropy(data)
        assert 3.0 < entropy < 5.5  # normal code range


# ---------------------------------------------------------------------------
# Compression ratio helper
# ---------------------------------------------------------------------------

class TestCompressionRatio:
    def test_empty(self):
        assert _compression_ratio(b"") == 1.0

    def test_repetitive_compresses_well(self):
        data = b"x" * 10000
        ratio = _compression_ratio(data)
        assert ratio < 0.05  # should compress very well

    def test_random_compresses_poorly(self):
        import os
        data = os.urandom(1000)
        ratio = _compression_ratio(data)
        assert ratio > 0.8  # random data doesn't compress well


# ---------------------------------------------------------------------------
# get_pr_effective_changes — integration with file records
# ---------------------------------------------------------------------------

class TestGetPrEffectiveChanges:
    def test_no_files_falls_back_to_pr_counts(self):
        user = make_user(id=1, login="alice")
        repo = make_repo(id=1, name="repo", owner=user)
        pr = make_pr(1, user, repo, additions=100, deletions=50)
        bundle = make_bundle(users=[user], repositories=[repo], pull_requests=[pr])
        ctx = make_context(bundle, user_login="alice")
        eff_add, eff_del, gen = get_pr_effective_changes(ctx.ledger, pr)
        assert eff_add == 100
        assert eff_del == 50
        assert gen == 0

    def test_excludes_generated_files(self):
        user = make_user(id=1, login="alice")
        repo = make_repo(id=1, name="repo", owner=user)
        pr = make_pr(1, user, repo, additions=200, deletions=100)
        files = [
            make_file("a1", "src/main.py", additions=80, deletions=30, changes=110, pr_number=1),
            make_file("a2", "package-lock.json", additions=120, deletions=70, changes=190, pr_number=1),
        ]
        bundle = make_bundle(users=[user], repositories=[repo], pull_requests=[pr], files=files)
        ctx = make_context(bundle, user_login="alice")
        eff_add, eff_del, gen = get_pr_effective_changes(ctx.ledger, pr)
        assert eff_add == 80
        assert eff_del == 30
        assert gen == 190  # 120 + 70

    def test_all_generated(self):
        user = make_user(id=1, login="alice")
        repo = make_repo(id=1, name="repo", owner=user)
        pr = make_pr(1, user, repo, additions=100, deletions=50)
        files = [
            make_file("a1", "yarn.lock", additions=100, deletions=50, changes=150, pr_number=1),
        ]
        bundle = make_bundle(users=[user], repositories=[repo], pull_requests=[pr], files=files)
        ctx = make_context(bundle, user_login="alice")
        eff_add, eff_del, gen = get_pr_effective_changes(ctx.ledger, pr)
        assert eff_add == 0
        assert eff_del == 0
        assert gen == 150


# ---------------------------------------------------------------------------
# PR size distribution — generated-file filtering integration
# ---------------------------------------------------------------------------

class TestPRSizeDistributionGeneratedFilter:
    def test_lockfile_excluded_changes_size_category(self):
        """A PR that is 'medium' by raw lines becomes 'trivial' after excluding lockfile."""
        user = make_user(id=1, login="alice")
        repo = make_repo(id=1, name="repo", owner=user)
        # PR with 5 real lines + 500 lockfile lines
        pr = make_pr(1, user, repo, additions=505, deletions=0)
        files = [
            make_file("a1", "src/config.py", additions=5, deletions=0, changes=5, pr_number=1),
            make_file("a2", "poetry.lock", additions=500, deletions=0, changes=500, pr_number=1),
        ]
        bundle = make_bundle(users=[user], repositories=[repo], pull_requests=[pr], files=files)
        ctx = make_context(bundle, user_login="alice")

        metric = PRSizeDistribution()
        res = metric.run(ctx)
        # Effective: 5 additions + 0 deletions * 0.5 = 5 weighted → trivial
        assert 1 in res.details["trivial_pr_numbers"]
        assert res.details["generated_lines_excluded"] == 500

    def test_no_generated_files_unchanged(self):
        """PR with no generated files: raw and effective are the same."""
        user = make_user(id=1, login="alice")
        repo = make_repo(id=1, name="repo", owner=user)
        pr = make_pr(1, user, repo, additions=100, deletions=50)
        files = [
            make_file("a1", "src/main.py", additions=100, deletions=50, changes=150, pr_number=1),
        ]
        bundle = make_bundle(users=[user], repositories=[repo], pull_requests=[pr], files=files)
        ctx = make_context(bundle, user_login="alice")

        metric = PRSizeDistribution()
        res = metric.run(ctx)
        assert res.details["generated_lines_excluded"] == 0
        assert res.details["medium_pr_count"] == 1  # 100 + 50*0.5 = 125 → medium


# ---------------------------------------------------------------------------
# Trivial contribution rate — generated-file filtering integration
# ---------------------------------------------------------------------------

class TestTrivialContributionRateGeneratedFilter:
    def test_lockfile_pr_becomes_trivial(self):
        """A PR that looks non-trivial by raw lines becomes trivial after excluding generated."""
        user = make_user(id=1, login="alice")
        repo = make_repo(id=1, name="repo", owner=user)
        start = DEFAULT_START
        pr = make_pr(1, user, repo, additions=505, deletions=0, base_time=start)
        files = [
            make_file("a1", "src/fix.py", additions=5, deletions=0, changes=5, pr_number=1),
            make_file("a2", "package-lock.json", additions=500, deletions=0, changes=500, pr_number=1),
        ]
        bundle = make_bundle(users=[user], repositories=[repo], pull_requests=[pr], files=files)
        ctx = make_context(bundle, user_login="alice", start_date=start, end_date=start + timedelta(days=30))

        metric = TrivialContributionRate()
        res = metric.run(ctx)
        assert res.details["trivial_pr_count"] == 1
        assert 1 in res.details["trivial_pr_numbers"]
        assert res.details["generated_lines_excluded"] == 500


# ---------------------------------------------------------------------------
# parse_hunks — function-level hunk parsing (Phase 1c)
# ---------------------------------------------------------------------------

class TestParseHunks:
    def test_empty_patch(self):
        assert parse_hunks(None) == []
        assert parse_hunks("") == []

    def test_single_hunk_with_context(self):
        patch = (
            "@@ -10,5 +10,7 @@ def my_function():\n"
            " existing line\n"
            "+new line 1\n"
            "+new line 2\n"
            " another existing\n"
        )
        hunks = parse_hunks(patch)
        assert len(hunks) == 1
        assert hunks[0]["old_start"] == 10
        assert hunks[0]["old_count"] == 5
        assert hunks[0]["new_start"] == 10
        assert hunks[0]["new_count"] == 7
        assert hunks[0]["function_context"] == "def my_function():"
        assert hunks[0]["added_lines"] == 2
        assert hunks[0]["removed_lines"] == 0

    def test_multiple_hunks(self):
        patch = (
            "@@ -1,3 +1,4 @@ class Foo:\n"
            " line\n"
            "+added\n"
            "@@ -20,5 +21,3 @@ def bar():\n"
            " line\n"
            "-removed1\n"
            "-removed2\n"
        )
        hunks = parse_hunks(patch)
        assert len(hunks) == 2
        assert hunks[0]["function_context"] == "class Foo:"
        assert hunks[0]["added_lines"] == 1
        assert hunks[0]["removed_lines"] == 0
        assert hunks[1]["function_context"] == "def bar():"
        assert hunks[1]["added_lines"] == 0
        assert hunks[1]["removed_lines"] == 2

    def test_hunk_without_context(self):
        patch = (
            "@@ -0,0 +1,3 @@\n"
            "+line 1\n"
            "+line 2\n"
            "+line 3\n"
        )
        hunks = parse_hunks(patch)
        assert len(hunks) == 1
        assert hunks[0]["function_context"] is None
        assert hunks[0]["added_lines"] == 3

    def test_real_world_ts_context(self):
        """Test with realistic TypeScript-style hunk context."""
        patch = (
            "@@ -49,3 +49,4 @@ export {\n"
            " existing\n"
            "+  KebabMenuButton,\n"
        )
        hunks = parse_hunks(patch)
        assert len(hunks) == 1
        assert hunks[0]["function_context"] == "export {"

    def test_mixed_adds_and_removes(self):
        patch = (
            "@@ -5,4 +5,4 @@ def process():\n"
            " ctx\n"
            "-old_val = 1\n"
            "+new_val = 2\n"
            " more\n"
        )
        hunks = parse_hunks(patch)
        assert hunks[0]["added_lines"] == 1
        assert hunks[0]["removed_lines"] == 1


# ---------------------------------------------------------------------------
# is_test_content — patch-content test detection (Phase 1d)
# ---------------------------------------------------------------------------

class TestIsTestContent:
    def test_empty(self):
        assert not is_test_content(None)
        assert not is_test_content("")

    def test_python_pytest_import(self):
        patch = "@@ -0,0 +1,3 @@\n+import pytest\n+\n+def test_hello():\n+    assert True\n"
        assert is_test_content(patch)

    def test_python_unittest(self):
        patch = "@@ -0,0 +1,3 @@\n+from unittest import TestCase\n+class MyTest(TestCase):\n"
        assert is_test_content(patch)

    def test_python_test_function(self):
        patch = "@@ -0,0 +1,3 @@\n+def test_my_feature():\n+    result = compute()\n+    assert result == 42\n"
        assert is_test_content(patch)

    def test_js_describe_it(self):
        patch = "@@ -0,0 +1,5 @@\n+describe('MyComponent', () => {\n+  it('should render', () => {\n+    expect(true).toBe(true);\n+  });\n+});\n"
        assert is_test_content(patch)

    def test_js_jest_import(self):
        patch = "@@ -0,0 +1,2 @@\n+import { render, screen } from '@testing-library/react';\n"
        assert is_test_content(patch)

    def test_java_test_annotation(self):
        patch = "@@ -0,0 +1,4 @@\n+@Test\n+public void shouldWork() {\n+    assertEquals(1, 1);\n+}\n"
        assert is_test_content(patch)

    def test_rust_test_attribute(self):
        patch = "@@ -0,0 +1,4 @@\n+#[test]\n+fn test_add() {\n+    assert_eq!(2 + 2, 4);\n+}\n"
        assert is_test_content(patch)

    def test_go_test_function(self):
        patch = "@@ -0,0 +1,4 @@\n+func TestAdd(t *testing.T) {\n+    if add(2, 3) != 5 {\n+        t.Error(\"wrong\")\n+    }\n+}\n"
        assert is_test_content(patch)

    def test_normal_code_not_test(self):
        patch = "@@ -1,3 +1,5 @@\n def hello():\n-    print('hello')\n+    print('hello world')\n+    return True\n"
        assert not is_test_content(patch)

    def test_only_removed_test_code_not_detected(self):
        """Removed lines should not trigger test detection."""
        patch = "@@ -1,3 +1,1 @@\n-import pytest\n-def test_old():\n-    pass\n+# cleaned up\n"
        assert not is_test_content(patch)


class TestIsTestFileOrContent:
    def test_path_match(self):
        assert is_test_file_or_content("tests/test_foo.py")

    def test_content_match(self):
        patch = "@@ -0,0 +1,2 @@\n+import pytest\n+def test_bar():\n"
        assert is_test_file_or_content("src/helpers.py", patch)

    def test_neither(self):
        patch = "@@ -1,2 +1,2 @@\n-x = 1\n+x = 2\n"
        assert not is_test_file_or_content("src/main.py", patch)


# ---------------------------------------------------------------------------
# classify_diff_structure — structural diff classification (Phase 1e)
# ---------------------------------------------------------------------------

class TestClassifyDiffStructure:
    def test_empty(self):
        assert classify_diff_structure(None) == {}
        assert classify_diff_structure("") == {}

    def test_new_function(self):
        patch = (
            "@@ -0,0 +1,5 @@\n"
            "+def process_data(items):\n"
            "+    result = []\n"
            "+    for item in items:\n"
            "+        result.append(item * 2)\n"
            "+    return result\n"
        )
        result = classify_diff_structure(patch)
        assert result.get("new_function", 0) >= 1

    def test_new_class(self):
        patch = (
            "@@ -0,0 +1,3 @@\n"
            "+class UserService:\n"
            "+    def __init__(self):\n"
            "+        self.users = []\n"
        )
        result = classify_diff_structure(patch)
        assert result.get("new_class", 0) >= 1

    def test_conditional_change(self):
        patch = (
            "@@ -5,3 +5,5 @@\n"
            " x = get_value()\n"
            "+if x > threshold:\n"
            "+    handle_overflow(x)\n"
            " return x\n"
        )
        result = classify_diff_structure(patch)
        assert result.get("conditional_change", 0) >= 1

    def test_import_change(self):
        patch = (
            "@@ -1,2 +1,3 @@\n"
            " import os\n"
            "+import json\n"
            "+from pathlib import Path\n"
        )
        result = classify_diff_structure(patch)
        assert result.get("import_change", 0) >= 1

    def test_whitespace_only(self):
        patch = (
            "@@ -1,3 +1,3 @@\n"
            "-  x = 1\n"
            "+    x = 1\n"
        )
        # Only whitespace differs in the added content
        result = classify_diff_structure(patch)
        # Should detect as "other" or similar (not whitespace_only since content differs)
        assert isinstance(result, dict)

    def test_test_code_detection(self):
        patch = (
            "@@ -0,0 +1,3 @@\n"
            "+def test_my_feature():\n"
            "+    result = compute(42)\n"
            "+    assert result == 84\n"
        )
        result = classify_diff_structure(patch)
        assert result.get("test_code", 0) >= 1

    def test_error_handling(self):
        patch = (
            "@@ -10,3 +10,7 @@\n"
            " data = fetch()\n"
            "+try:\n"
            "+    parsed = json.loads(data)\n"
            "+except json.JSONDecodeError:\n"
            "+    parsed = {}\n"
        )
        result = classify_diff_structure(patch)
        assert result.get("error_handling", 0) >= 1

    def test_mixed_categories(self):
        patch = (
            "@@ -0,0 +1,6 @@\n"
            "+import logging\n"
            "+def new_handler():\n"
            "+    if condition:\n"
            "+        try:\n"
            "+            process()\n"
            "+        except Exception:\n"
        )
        result = classify_diff_structure(patch)
        # Should have multiple categories
        assert len(result) >= 2


# ---------------------------------------------------------------------------
# Phase 2a: Pygments-based code block analysis
# ---------------------------------------------------------------------------


class TestExtractCodeBlocks:
    def test_no_code_blocks(self):
        assert extract_code_blocks("Just a plain comment.") == []

    def test_empty_input(self):
        assert extract_code_blocks("") == []
        assert extract_code_blocks(None) == []

    def test_single_fenced_block_with_language(self):
        text = "Check this:\n```python\ndef foo():\n    return 42\n```\nThoughts?"
        blocks = extract_code_blocks(text)
        assert len(blocks) == 1
        assert blocks[0][0] == "python"
        assert "def foo():" in blocks[0][1]

    def test_single_fenced_block_no_language(self):
        text = "Try:\n```\nx = 1\n```"
        blocks = extract_code_blocks(text)
        assert len(blocks) == 1
        assert blocks[0][0] is None
        assert "x = 1" in blocks[0][1]

    def test_multiple_blocks(self):
        text = "Before:\n```js\nconst a = 1;\n```\nAfter:\n```python\nx = 2\n```"
        blocks = extract_code_blocks(text)
        assert len(blocks) == 2
        assert blocks[0][0] == "js"
        assert blocks[1][0] == "python"

    def test_empty_code_block_skipped(self):
        text = "Empty:\n```python\n\n```\nEnd"
        blocks = extract_code_blocks(text)
        assert len(blocks) == 0  # empty content stripped away


class TestScoreCodeBlockQuality:
    def test_empty_code(self):
        assert score_code_block_quality("") == 0.0
        assert score_code_block_quality("   ") == 0.0

    def test_plain_text_in_code_block(self):
        # Plain text should get a low score
        score = score_code_block_quality("just some text here")
        assert score <= 0.6  # not a high code quality score

    def test_trivial_snippet(self):
        # Very short code — minimal credit
        score = score_code_block_quality("x = 1", "python")
        assert 0.2 <= score <= 0.8

    def test_substantive_python_code(self):
        code = (
            "def calculate_average(values: list[float]) -> float:\n"
            "    if not values:\n"
            "        return 0.0\n"
            "    return sum(values) / len(values)\n"
        )
        score = score_code_block_quality(code, "python")
        assert score >= 0.6  # real code should score well

    def test_substantive_javascript_code(self):
        code = (
            "function processItems(items) {\n"
            "    return items\n"
            "        .filter(item => item.active)\n"
            "        .map(item => ({ ...item, processed: true }));\n"
            "}\n"
        )
        score = score_code_block_quality(code, "javascript")
        assert score >= 0.6

    def test_language_alias_resolution(self):
        code = "x: int = sum(range(10))\nprint(x)\ny = x * 2"
        # "py" should resolve to "python" lexer
        score_py = score_code_block_quality(code, "py")
        score_python = score_code_block_quality(code, "python")
        assert score_py == score_python

    def test_unknown_language_falls_back_to_guess(self):
        code = "def hello():\n    print('hello')\n    return True\n"
        score = score_code_block_quality(code, "nonexistent_lang_xyz")
        assert score > 0.0  # should still produce a score via guess_lexer

    def test_real_code_beats_plain_text(self):
        real_code = (
            "async function fetchData(url: string): Promise<Response> {\n"
            "    const response = await fetch(url);\n"
            "    if (!response.ok) {\n"
            "        throw new Error(`HTTP ${response.status}`);\n"
            "    }\n"
            "    return response;\n"
            "}\n"
        )
        plain = "This is just a regular sentence with no code at all."
        assert score_code_block_quality(real_code, "typescript") > score_code_block_quality(plain)


class TestScoreCommentCodeQuality:
    def test_no_code(self):
        assert score_comment_code_quality("Just a plain comment.") == 0

    def test_inline_backticks_only(self):
        assert score_comment_code_quality("Use `foo()` instead of `bar()`.") == 10

    def test_fenced_code_block_scores_above_inline(self):
        body = "Try this:\n```python\ndef better():\n    return sorted(items)\n```"
        score = score_comment_code_quality(body)
        assert score >= 10  # at least as much as inline backticks
        assert score <= 25  # capped at 25

    def test_trivial_code_block_still_gets_minimum(self):
        body = "Use:\n```\nx\n```"
        score = score_comment_code_quality(body)
        assert score >= 10  # floor

    def test_substantive_code_gets_near_max(self):
        body = (
            "Consider this approach:\n"
            "```python\n"
            "def process_batch(items: list[dict]) -> list[Result]:\n"
            "    results = []\n"
            "    for item in items:\n"
            "        if item.get('active'):\n"
            "            result = transform(item)\n"
            "            results.append(result)\n"
            "    return results\n"
            "```\n"
        )
        score = score_comment_code_quality(body)
        assert score >= 20  # substantive code should score high

    def test_multiple_blocks_uses_best(self):
        body = (
            "Bad:\n```\nx\n```\n"
            "Good:\n```python\n"
            "def compute(a: int, b: int) -> int:\n"
            "    return a + b\n"
            "```"
        )
        score = score_comment_code_quality(body)
        # Should use the better block's score
        assert score >= 15


class TestScoreCommentIntegration:
    """Test that Pygments-enhanced scoring integrates correctly with _score_comment."""

    def test_code_block_comment_scores_higher_than_plain(self):
        from impact.metrics.plugins.influence.review_comment_substance import _score_comment
        plain = "This is a comment about the code quality and structure."
        with_code = (
            "Consider refactoring like this:\n"
            "```python\n"
            "def improved_handler(request):\n"
            "    validated = validate(request)\n"
            "    if not validated:\n"
            "        raise ValueError('Invalid')\n"
            "    return process(validated)\n"
            "```\n"
        )
        assert _score_comment(with_code) > _score_comment(plain)

    def test_score_comment_preserves_other_signals(self):
        from impact.metrics.plugins.influence.review_comment_substance import _score_comment
        # A comment with code + question + actionable language should score high
        body = (
            "Should we consider this approach instead?\n"
            "```python\n"
            "def better_way(data):\n"
            "    return sorted(data, key=lambda x: x.priority)\n"
            "```\n"
            "See https://docs.python.org/3/howto/sorting.html for reference."
        )
        score = _score_comment(body)
        # Length >= 100 (30) + code (10-25) + question (15) + link (10) + actionable (10)
        assert score >= 65


# ---------------------------------------------------------------------------
# Phase 2b: Manifest-aware module detection
# ---------------------------------------------------------------------------


class TestDetectModuleBoundary:
    def test_empty_path(self):
        assert detect_module_boundary("") == "unknown"

    def test_root_level_file(self):
        assert detect_module_boundary("main.py") == "main.py"
        assert detect_module_boundary(".gitignore") == ".gitignore"

    def test_simple_directory(self):
        assert detect_module_boundary("backend/api/routes.py") == "backend"
        assert detect_module_boundary("frontend/src/App.tsx") == "frontend"

    def test_workspace_packages(self):
        assert detect_module_boundary("frontend/packages/core/src/utils.ts") == "frontend/packages/core"
        assert detect_module_boundary("frontend/packages/ui/components/Button.tsx") == "frontend/packages/ui"

    def test_workspace_plugins(self):
        assert detect_module_boundary("superset-frontend/plugins/chart-echarts/src/index.ts") == "superset-frontend/plugins/chart-echarts"

    def test_workspace_apps(self):
        assert detect_module_boundary("apps/web/src/main.ts") == "apps/web"
        assert detect_module_boundary("apps/api/routes/health.py") == "apps/api"

    def test_workspace_services(self):
        assert detect_module_boundary("services/auth/handler.go") == "services/auth"
        assert detect_module_boundary("services/billing/models.py") == "services/billing"

    def test_workspace_libs(self):
        assert detect_module_boundary("libs/shared/utils.ts") == "libs/shared"

    def test_workspace_crates(self):
        assert detect_module_boundary("crates/core/src/lib.rs") == "crates/core"

    def test_nested_workspace(self):
        # When workspace dir is at depth > 0
        assert detect_module_boundary("mono/packages/auth/src/login.ts") == "mono/packages/auth"

    def test_manifest_file_identifies_module_root(self):
        assert detect_module_boundary("frontend/packages/core/package.json") == "frontend/packages/core"
        assert detect_module_boundary("services/api/go.mod") == "services/api"
        assert detect_module_boundary("backend/pyproject.toml") == "backend"

    def test_non_workspace_deep_path(self):
        # No workspace dir — falls back to top-level
        assert detect_module_boundary("src/components/ui/Button.tsx") == "src"


class TestBuildModuleMap:
    def test_simple_map(self):
        paths = [
            "frontend/src/App.tsx",
            "backend/api.py",
            "main.py",
        ]
        module_map = build_module_map(paths)
        assert module_map["frontend/src/App.tsx"] == "frontend"
        assert module_map["backend/api.py"] == "backend"
        assert module_map["main.py"] == "main.py"

    def test_workspace_detection(self):
        paths = [
            "frontend/packages/core/src/utils.ts",
            "frontend/packages/ui/Button.tsx",
            "frontend/src/App.tsx",
        ]
        module_map = build_module_map(paths)
        assert module_map["frontend/packages/core/src/utils.ts"] == "frontend/packages/core"
        assert module_map["frontend/packages/ui/Button.tsx"] == "frontend/packages/ui"
        assert module_map["frontend/src/App.tsx"] == "frontend"

    def test_manifest_confirms_module_root(self):
        paths = [
            "lib/core/package.json",  # manifest file
            "lib/core/src/index.ts",
            "lib/core/src/utils.ts",
        ]
        module_map = build_module_map(paths)
        # Manifest confirms lib/core as a module root
        assert module_map["lib/core/src/index.ts"] == "lib/core"
        assert module_map["lib/core/src/utils.ts"] == "lib/core"

    def test_monorepo_superset_pattern(self):
        paths = [
            "superset-frontend/src/components/Button.tsx",
            "superset-frontend/packages/superset-ui-core/src/utils.ts",
            "superset-frontend/plugins/chart-echarts/src/index.ts",
            "superset/models/sql_lab.py",
            "tests/integration_tests/test_api.py",
        ]
        module_map = build_module_map(paths)
        modules = set(module_map.values())
        assert "superset-frontend" in modules
        assert "superset-frontend/packages/superset-ui-core" in modules
        assert "superset-frontend/plugins/chart-echarts" in modules
        assert "superset" in modules
        assert "tests" in modules
        # Should produce 5 distinct modules, not just 3 top-level dirs
        assert len(modules) == 5


# ---------------------------------------------------------------------------
# Phase 3: tree-sitter function identity + trivial detection
# ---------------------------------------------------------------------------


class TestParseFunctionsPython:
    def test_simple_function(self):
        code = "def hello():\n    print('hi')\n"
        funcs = parse_functions(code, "main.py")
        assert len(funcs) == 1
        assert funcs[0]["name"] == "hello"
        assert funcs[0]["kind"] == "function"
        assert funcs[0]["is_trivial"] is True  # single statement

    def test_complex_function(self):
        code = (
            "def process(items, threshold):\n"
            "    results = []\n"
            "    for item in items:\n"
            "        if item.value > threshold:\n"
            "            results.append(item)\n"
            "    return results\n"
        )
        funcs = parse_functions(code, "core.py")
        assert len(funcs) == 1
        f = funcs[0]
        assert f["name"] == "process"
        assert f["parameter_count"] == 2
        assert f["body_statement_count"] >= 2
        assert f["is_trivial"] is False

    def test_class_methods(self):
        code = (
            "class Service:\n"
            "    def __init__(self, config):\n"
            "        self.config = config\n"
            "    def get_name(self):\n"
            "        return self.config.name\n"
            "    def process(self, data):\n"
            "        validated = self.validate(data)\n"
            "        result = self.transform(validated)\n"
            "        return result\n"
        )
        funcs = parse_functions(code, "service.py")
        assert len(funcs) == 3
        kinds = {f["name"]: f["kind"] for f in funcs}
        assert kinds["__init__"] == "method"
        assert kinds["get_name"] == "method"
        assert kinds["process"] == "method"
        # __init__ and get_name are trivial (1 statement each)
        trivial_map = {f["name"]: f["is_trivial"] for f in funcs}
        assert trivial_map["__init__"] is True
        assert trivial_map["get_name"] is True
        assert trivial_map["process"] is False

    def test_empty_function(self):
        code = "def noop():\n    pass\n"
        funcs = parse_functions(code, "empty.py")
        assert len(funcs) == 1
        assert funcs[0]["is_trivial"] is True

    def test_line_numbers(self):
        code = (
            "# comment\n"
            "def first():\n"
            "    return 1\n"
            "\n"
            "def second():\n"
            "    return 2\n"
        )
        funcs = parse_functions(code, "lines.py")
        assert len(funcs) == 2
        assert funcs[0]["start_line"] == 2
        assert funcs[1]["start_line"] == 5


class TestParseFunctionsJavaScript:
    def test_function_declaration(self):
        code = "function getData() {\n    return fetch('/api');\n}\n"
        funcs = parse_functions(code, "api.js")
        assert len(funcs) == 1
        assert funcs[0]["name"] == "getData"
        assert funcs[0]["is_trivial"] is True

    def test_class_method(self):
        code = (
            "class Service {\n"
            "    constructor(config) {\n"
            "        this.config = config;\n"
            "    }\n"
            "    getName() {\n"
            "        return this.config.name;\n"
            "    }\n"
            "}\n"
        )
        funcs = parse_functions(code, "service.js")
        constructors = [f for f in funcs if f["kind"] == "constructor"]
        methods = [f for f in funcs if f["kind"] == "method"]
        assert len(constructors) == 1
        assert len(methods) >= 1


class TestParseFunctionsTypeScript:
    def test_ts_function(self):
        code = "function greet(name: string): string {\n    return `Hello, ${name}`;\n}\n"
        funcs = parse_functions(code, "greet.ts")
        assert len(funcs) == 1
        assert funcs[0]["name"] == "greet"

    def test_tsx_file(self):
        code = "function Component(props: Props) {\n    return null;\n}\n"
        funcs = parse_functions(code, "Component.tsx")
        assert len(funcs) == 1


class TestParseFunctionsGo:
    def test_simple_func(self):
        code = "package main\n\nfunc getID() int {\n    return 42\n}\n"
        funcs = parse_functions(code, "main.go")
        assert len(funcs) == 1
        assert funcs[0]["name"] == "getID"
        assert funcs[0]["is_trivial"] is True

    def test_complex_func(self):
        code = (
            "package main\n\n"
            "func process(items []Item) []Result {\n"
            "    var results []Result\n"
            "    for _, item := range items {\n"
            "        results = append(results, item)\n"
            "    }\n"
            "    return results\n"
            "}\n"
        )
        funcs = parse_functions(code, "handler.go")
        assert len(funcs) == 1
        assert funcs[0]["body_statement_count"] >= 2
        assert funcs[0]["is_trivial"] is False


class TestParseFunctionsRust:
    def test_simple_fn(self):
        code = "fn get_id() -> u32 {\n    42\n}\n"
        funcs = parse_functions(code, "lib.rs")
        assert len(funcs) == 1
        assert funcs[0]["name"] == "get_id"
        assert funcs[0]["is_trivial"] is True  # single expression

    def test_complex_fn(self):
        code = (
            "fn process(items: Vec<Item>) -> Vec<Result> {\n"
            "    let mut results = Vec::new();\n"
            "    for item in items {\n"
            "        results.push(item);\n"
            "    }\n"
            "    results\n"
            "}\n"
        )
        funcs = parse_functions(code, "processor.rs")
        assert len(funcs) == 1
        assert funcs[0]["is_trivial"] is False


class TestParseFunctionsJava:
    def test_getter(self):
        code = (
            "class Foo {\n"
            "    public String getName() {\n"
            "        return this.name;\n"
            "    }\n"
            "}\n"
        )
        funcs = parse_functions(code, "Foo.java")
        assert len(funcs) == 1
        assert funcs[0]["name"] == "getName"
        assert funcs[0]["is_trivial"] is True

    def test_complex_method(self):
        code = (
            "class Service {\n"
            "    public void process(List<User> users) {\n"
            "        for (User user : users) {\n"
            "            if (user.isActive()) {\n"
            "                notify(user);\n"
            "            }\n"
            "        }\n"
            "        log.info(\"done\");\n"
            "    }\n"
            "}\n"
        )
        funcs = parse_functions(code, "Service.java")
        assert len(funcs) == 1
        assert funcs[0]["is_trivial"] is False


class TestParseFunctionsEdgeCases:
    def test_unsupported_extension(self):
        assert parse_functions("some content", "file.xyz") == []

    def test_empty_content(self):
        assert parse_functions("", "empty.py") == []

    def test_invalid_syntax(self):
        # tree-sitter is error-tolerant so it should still return something
        code = "def broken(\n    return\n"
        funcs = parse_functions(code, "broken.py")
        # Should not crash; may or may not find a function
        assert isinstance(funcs, list)

    def test_no_functions(self):
        code = "x = 1\ny = 2\nprint(x + y)\n"
        funcs = parse_functions(code, "script.py")
        assert funcs == []


class TestComputeTrivialRatio:
    def test_empty_list(self):
        assert compute_trivial_ratio([]) == 0.0

    def test_all_trivial(self):
        funcs = [
            {"name": "a", "kind": "function", "start_line": 1, "end_line": 2,
             "parameter_count": 0, "body_statement_count": 1, "is_trivial": True},
            {"name": "b", "kind": "function", "start_line": 3, "end_line": 4,
             "parameter_count": 0, "body_statement_count": 0, "is_trivial": True},
        ]
        assert compute_trivial_ratio(funcs) == 1.0

    def test_mixed(self):
        funcs = [
            {"name": "a", "kind": "function", "start_line": 1, "end_line": 2,
             "parameter_count": 0, "body_statement_count": 1, "is_trivial": True},
            {"name": "b", "kind": "function", "start_line": 3, "end_line": 10,
             "parameter_count": 2, "body_statement_count": 5, "is_trivial": False},
        ]
        assert compute_trivial_ratio(funcs) == 0.5


class TestAnalyzeFileComplexity:
    def test_python_file(self):
        code = (
            "def trivial():\n"
            "    return 1\n"
            "\n"
            "def complex_fn(x, y):\n"
            "    result = x + y\n"
            "    if result > 10:\n"
            "        return result\n"
            "    return 0\n"
        )
        result = analyze_file_complexity(code, "math.py")
        assert result["function_count"] == 2
        assert result["trivial_count"] == 1
        assert 0.0 < result["trivial_ratio"] < 1.0

    def test_unsupported_returns_empty(self):
        result = analyze_file_complexity("content", "file.xyz")
        assert result == {}


# ---------------------------------------------------------------------------
# _parse_hunk_lines — counts only actual changed lines, not context
# ---------------------------------------------------------------------------


class TestParseHunkLines:
    def test_empty_patch(self):
        assert _parse_hunk_lines(None) == set()
        assert _parse_hunk_lines("") == set()

    def test_added_lines_only(self):
        patch = (
            "@@ -0,0 +1,3 @@\n"
            "+line 1\n"
            "+line 2\n"
            "+line 3\n"
        )
        result = _parse_hunk_lines(patch, "+")
        assert result == {1, 2, 3}

    def test_removed_lines_only(self):
        patch = (
            "@@ -5,3 +5,0 @@\n"
            "-old line 1\n"
            "-old line 2\n"
            "-old line 3\n"
        )
        result = _parse_hunk_lines(patch, "-")
        assert result == {5, 6, 7}

    def test_context_lines_excluded(self):
        """Context lines (starting with space) must NOT be counted as changed."""
        patch = (
            "@@ -10,5 +10,7 @@ def my_function():\n"
            " existing line\n"
            "+new line 1\n"
            "+new line 2\n"
            " another existing\n"
            " more existing\n"
        )
        # For the new side (+): only the two added lines
        added = _parse_hunk_lines(patch, "+")
        assert added == {11, 12}  # lines 10=context, 11=+, 12=+, 13=context, 14=context

        # For the old side (-): no removed lines in this patch
        removed = _parse_hunk_lines(patch, "-")
        assert removed == set()

    def test_mixed_adds_removes_context(self):
        """Correctly tracks line numbers through mixed additions, removals, and context."""
        patch = (
            "@@ -5,4 +5,4 @@ def process():\n"
            " ctx\n"
            "-old_val = 1\n"
            "+new_val = 2\n"
            " more\n"
        )
        added = _parse_hunk_lines(patch, "+")
        assert added == {6}  # line 5=context, skip -, line 6=+, line 7=context

        removed = _parse_hunk_lines(patch, "-")
        assert removed == {6}  # old line 5=context, old line 6=-

    def test_multiple_hunks(self):
        patch = (
            "@@ -1,2 +1,3 @@\n"
            " line1\n"
            "+added_first\n"
            " line2\n"
            "@@ -10,2 +11,3 @@\n"
            " line10\n"
            "+added_second\n"
            " line11\n"
        )
        added = _parse_hunk_lines(patch, "+")
        assert added == {2, 12}  # first hunk: ctx@1, add@2, ctx@3; second hunk: ctx@11, add@12, ctx@13

    def test_no_inflation_from_context(self):
        """Key regression test: old impl used hunk header counts which included context lines.
        A hunk @@ -10,5 +10,7 @@ with 2 added lines + 3 context lines used to return
        {10, 11, 12, 13, 14, 15, 16} (7 lines) instead of just the 2 actual additions."""
        patch = (
            "@@ -10,5 +10,7 @@ def foo():\n"
            " ctx1\n"
            " ctx2\n"
            "+add1\n"
            "+add2\n"
            " ctx3\n"
            " ctx4\n"
            " ctx5\n"
        )
        added = _parse_hunk_lines(patch, "+")
        # Should be exactly 2 lines, not 7
        assert len(added) == 2
        assert added == {12, 13}


# ---------------------------------------------------------------------------
# is_dependency_file — strict basename matching (no false positives)
# ---------------------------------------------------------------------------


class TestIsDependencyFile:
    def test_exact_basenames_match(self):
        assert is_dependency_file("package.json")
        assert is_dependency_file("frontend/package.json")
        assert is_dependency_file("requirements.txt")
        assert is_dependency_file("deep/path/pyproject.toml")
        assert is_dependency_file("Cargo.toml")
        assert is_dependency_file("go.mod")
        assert is_dependency_file("pom.xml")

    def test_no_substring_false_positives(self):
        """Files containing dep filenames as substrings must NOT match."""
        assert not is_dependency_file("my_package.json_backup")
        assert not is_dependency_file("not_requirements.txt.bak")
        assert not is_dependency_file("src/cargo.toml.template")
        # But the basename itself still matches
        assert is_dependency_file("src/cargo.toml")

    def test_non_dep_files(self):
        assert not is_dependency_file("main.py")
        assert not is_dependency_file("src/components/Button.tsx")
        assert not is_dependency_file("")
        assert not is_dependency_file("README.md")

    def test_case_insensitive(self):
        assert is_dependency_file("PACKAGE.JSON")
        assert is_dependency_file("Gemfile")
        assert is_dependency_file("Pipfile.lock")


# ---------------------------------------------------------------------------
# is_documentation_file — strict matching (no false positives)
# ---------------------------------------------------------------------------


class TestIsDocumentationFile:
    def test_markdown_files(self):
        assert is_documentation_file("README.md")
        assert is_documentation_file("docs/guide.md")
        assert is_documentation_file("CHANGELOG.rst")
        assert is_documentation_file("notes.adoc")

    def test_doc_directories(self):
        assert is_documentation_file("docs/api.py")
        assert is_documentation_file("doc/setup.txt")
        assert is_documentation_file("documentation/index.html")
        assert is_documentation_file("wiki/page.md")

    def test_doc_basenames(self):
        assert is_documentation_file("LICENSE")
        assert is_documentation_file("CONTRIBUTING.md")
        assert is_documentation_file("AUTHORS")
        assert is_documentation_file("mkdocs.yml")

    def test_no_false_positives(self):
        """Common false positive cases from the old substring matching."""
        # .md extension still matches — this IS documentation
        # But non-doc files that happened to contain doc substrings:
        assert not is_documentation_file("markdown_parser.py")  # no .md extension
        assert not is_documentation_file("src/components/readme_generator.ts")  # basename doesn't match
        assert not is_documentation_file("main.py")
        assert not is_documentation_file("index.ts")  # not .html

    def test_empty_input(self):
        assert not is_documentation_file("")
        assert not is_documentation_file(None)


# ---------------------------------------------------------------------------
# is_conventional_commit — standard format validation
# ---------------------------------------------------------------------------


class TestIsConventionalCommit:
    def test_valid_conventional_commits(self):
        assert is_conventional_commit("feat: add login page")
        assert is_conventional_commit("fix: resolve crash on startup")
        assert is_conventional_commit("docs: update README")
        assert is_conventional_commit("chore: bump dependencies")
        assert is_conventional_commit("test: add unit tests for auth")
        assert is_conventional_commit("refactor: simplify parser logic")
        assert is_conventional_commit("ci: update GitHub Actions")

    def test_scoped_commits(self):
        assert is_conventional_commit("feat(auth): add OAuth support")
        assert is_conventional_commit("fix(api): handle 404 errors")

    def test_breaking_change(self):
        assert is_conventional_commit("feat!: drop Python 3.10 support")
        assert is_conventional_commit("fix(api)!: change response format")

    def test_non_conventional_commits(self):
        assert not is_conventional_commit("Add login page")
        assert not is_conventional_commit("Fixed the bug")
        assert not is_conventional_commit("WIP: working on feature")
        assert not is_conventional_commit("Merge branch 'main'")

    def test_empty_input(self):
        assert not is_conventional_commit("")
        assert not is_conventional_commit(None)

    def test_case_insensitive(self):
        assert is_conventional_commit("FEAT: uppercase")
        assert is_conventional_commit("Fix: mixed case")
