"""Tests for AI-Assisted PR Rate metric."""

import pytest
from datetime import datetime, timezone
from unittest.mock import MagicMock

from impact.domain.models import MetricContext
from impact.metrics.plugins.authored.ai_assisted_pr_rate import (
    AIAssistedPRRate,
    _detect_ai_assistance,
)


class TestDetectAIAssistance:
    """Test the _detect_ai_assistance helper function."""

    def test_detects_copilot_in_commit_message(self):
        text = "Add feature\n\nCo-authored-by: GitHub Copilot"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "copilot"

    def test_detects_cursor_in_title(self):
        text = "Fix bug (generated by Cursor)"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "cursor"

    def test_detects_claude_in_body(self):
        text = "This PR was generated with Claude Code assistance"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "claude"

    def test_detects_chatgpt(self):
        text = "Refactor function - generated by ChatGPT"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "chatgpt"

    def test_detects_generic_ai_generated(self):
        text = "Update docs (AI generated)"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "ai_assisted"

    def test_no_false_positives_for_normal_text(self):
        text = "This is a normal PR description about cursor movement"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is False
        assert tool is None

    def test_handles_none_text(self):
        is_ai, tool = _detect_ai_assistance(None)
        assert is_ai is False
        assert tool is None

    def test_handles_empty_text(self):
        is_ai, tool = _detect_ai_assistance("")
        assert is_ai is False
        assert tool is None

    def test_detects_cody(self):
        text = "Fix using Cody by Sourcegraph"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "cody"

    def test_detects_tabnine(self):
        text = "Completion via Tabnine"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "tabnine"

    # 2026 standard trailer detection tests
    def test_detects_generated_with_trailer_claude(self):
        """Test 2026 standard: Generated-with: Claude Code trailer."""
        text = "Add feature\n\nGenerated-with: Claude Code"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "claude"

    def test_detects_generated_by_trailer_cursor(self):
        """Test 2026 standard: Generated-by: Cursor trailer."""
        text = "Fix bug\n\nGenerated-by: Cursor"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "cursor"

    def test_detects_ai_generated_with_trailer_chatgpt(self):
        """Test 2026 standard: AI-generated-with: ChatGPT trailer."""
        text = "Refactor\n\nAI-generated-with: ChatGPT"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "chatgpt"

    def test_detects_generated_with_trailer_copilot(self):
        """Test 2026 standard: Generated-with: Copilot trailer."""
        text = "Feature\n\nGenerated-with: GitHub Copilot"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "copilot"

    def test_detects_generated_by_trailer_codewhisperer(self):
        """Test 2026 standard: Generated-by: CodeWhisperer trailer."""
        text = "Update\n\nGenerated-by: CodeWhisperer"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "codewhisperer"

    def test_detects_trailer_in_pr_body(self):
        """Test trailer detection in PR body."""
        text = "This PR adds new functionality.\n\nGenerated-with: Claude Code\n\nTests pass."
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "claude"

    def test_detects_trailer_case_insensitive(self):
        """Test trailers are case-insensitive."""
        text = "generated-WITH: cursor"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "cursor"

    def test_detects_trailer_underscore_variant(self):
        """Test Generated_with: variant (underscore instead of hyphen)."""
        text = "Generated_with: Claude"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "claude"

    def test_detects_generic_trailer_unknown_tool(self):
        """Test generic trailer with unknown tool still detects AI assistance."""
        text = "Generated-with: SomeNewAI"
        is_ai, tool = _detect_ai_assistance(text)
        assert is_ai is True
        assert tool == "ai_assisted"

    def test_trailer_does_not_false_positive(self):
        """Test that 'generated with' in normal prose doesn't trigger AI detection.
        
        Without a colon (Generated-with:) or AI tool name, normal prose should not
        be flagged as AI-assisted.
        """
        text = "This was generated with the help of my colleague"
        is_ai, tool = _detect_ai_assistance(text)
        # Normal prose without trailer syntax should NOT be flagged
        assert is_ai is False
        assert tool is None


def make_mock_pr(number: int, title: str, body: str = "", user_login: str = "testuser"):
    """Create a mock PR with all required attributes for filter_prs_for_contribution."""
    pr = MagicMock()
    pr.number = number
    pr.title = title
    pr.body = body
    pr.draft = False
    pr.merged = True
    pr.created_at = datetime(2024, 1, 15, tzinfo=timezone.utc)
    
    # Nested user mock
    user_mock = MagicMock()
    user_mock.login = user_login
    pr.user = user_mock
    
    return pr


def make_mock_commit(sha: str, message: str, user_login: str = "testuser"):
    """Create a mock commit with minimal required attributes."""
    commit = MagicMock()
    commit.sha = sha
    commit.message = message
    commit.date = datetime(2024, 1, 15, tzinfo=timezone.utc)
    
    # Nested author mock
    author_mock = MagicMock()
    author_mock.login = user_login
    commit.author = author_mock
    
    return commit


class TestAIAssistedPRRateMetric:
    """Test the AIAssistedPRRate metric class."""

    @pytest.fixture
    def metric(self):
        return AIAssistedPRRate()

    @pytest.fixture
    def mock_context(self):
        """Create a mock context with test PRs."""
        context = MagicMock(spec=MetricContext)
        context.user_login = "testuser"
        context.start_date = datetime(2024, 1, 1, tzinfo=timezone.utc)
        context.end_date = datetime(2024, 1, 31, tzinfo=timezone.utc)

        # Mock ledger
        ledger = MagicMock()
        context.ledger = ledger

        return context, ledger

    def test_metric_properties(self, metric):
        assert metric.slug == "ai_assisted_pr_rate"
        assert metric.name == "AI-Assisted PR Rate"
        assert metric.category == "contextual"
        assert "DevRank" in metric.frameworks

    def test_no_prs_returns_no_data(self, metric, mock_context):
        context, ledger = mock_context
        ledger.get_prs_for_user.return_value = []

        result = metric.run(context)

        assert result.metric_slug == "ai_assisted_pr_rate"
        assert result.details["total_pr_count"] == 0
        assert result.details["no_data"] is True
        assert "No PRs found" in result.summary

    def test_all_human_prs(self, metric, mock_context):
        context, ledger = mock_context

        # Create human PRs
        prs = [
            make_mock_pr(1, "Fix bug", "Manual fix"),
            make_mock_pr(2, "Add feature", "Implemented manually"),
        ]
        ledger.get_prs_for_user.return_value = prs
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        assert result.details["ai_rate"] == 0.0
        assert result.details["ai_pr_count"] == 0
        assert result.details["human_pr_count"] == 2
        assert result.details["total_pr_count"] == 2
        assert "0.0% AI-assisted" in result.summary

    def test_mixed_ai_and_human_prs(self, metric, mock_context):
        context, ledger = mock_context

        # Create mixed PRs
        human_pr = make_mock_pr(1, "Fix bug", "Manual fix")
        ai_pr = make_mock_pr(2, "Add feature (generated by Copilot)", "AI assisted implementation")
        prs = [human_pr, ai_pr]
        ledger.get_prs_for_user.return_value = prs
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        assert result.details["ai_rate"] == 50.0
        assert result.details["ai_pr_count"] == 1
        assert result.details["human_pr_count"] == 1
        assert "50.0% AI-assisted" in result.summary
        assert "copilot" in str(result.details["tool_breakdown"]).lower()

    def test_detects_ai_in_commit_messages(self, metric, mock_context):
        context, ledger = mock_context

        pr = make_mock_pr(1, "Update feature", "Some changes")
        ledger.get_prs_for_user.return_value = [pr]

        # AI detected in commit message
        ai_commit = make_mock_commit("abc123", "Add function\n\nGenerated by Claude Code")
        ledger.get_commits_for_pr.return_value = [ai_commit]

        result = metric.run(context)

        assert result.details["ai_rate"] == 100.0
        assert result.details["ai_pr_count"] == 1
        assert "claude" in str(result.details["tool_breakdown"]).lower()

    def test_tool_breakdown_aggregation(self, metric, mock_context):
        context, ledger = mock_context

        # Multiple PRs with different AI tools
        prs = [
            make_mock_pr(1, "Fix (Copilot)"),
            make_mock_pr(2, "Feature (Cursor)"),
            make_mock_pr(3, "Another (Copilot)"),
        ]
        ledger.get_prs_for_user.return_value = prs
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        breakdown = result.details["tool_breakdown"]
        assert breakdown["copilot"] == 2
        assert breakdown["cursor"] == 1

    def test_no_data_guard_short_period_low_count(self, metric, mock_context):
        context, ledger = mock_context
        context.start_date = datetime(2024, 1, 1, tzinfo=timezone.utc)
        context.end_date = datetime(2024, 1, 5, tzinfo=timezone.utc)  # Only 4 days

        # Only 2 PRs in short period
        prs = [
            make_mock_pr(1, "PR 1"),
            make_mock_pr(2, "PR 2"),
        ]
        ledger.get_prs_for_user.return_value = prs
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        # Should mark as no_data due to short period + low count
        assert result.details["no_data"] is True

    def test_sufficient_data_longer_period(self, metric, mock_context):
        context, ledger = mock_context
        # 20 days period with 2 PRs
        context.start_date = datetime(2024, 1, 1, tzinfo=timezone.utc)
        context.end_date = datetime(2024, 1, 21, tzinfo=timezone.utc)

        prs = [
            make_mock_pr(1, "PR 1"),
            make_mock_pr(2, "PR 2"),
        ]
        ledger.get_prs_for_user.return_value = prs
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        # Should NOT mark as no_data - longer period makes it valid
        assert result.details.get("no_data") is not True
        assert result.details["total_pr_count"] == 2

    def test_per_pr_evidence_structure(self, metric, mock_context):
        context, ledger = mock_context

        pr = make_mock_pr(1, "Feature by Copilot", "Generated with AI")
        ledger.get_prs_for_user.return_value = [pr]
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        per_pr = result.details["per_pr"]
        assert len(per_pr) == 1
        assert per_pr[0]["number"] == 1
        assert per_pr[0]["is_ai_assisted"] is True
        assert per_pr[0]["tool"] == "copilot"
        assert "evidence" in per_pr[0]
        # Evidence should contain source info
        assert any(e.get("source") in ["pr_title", "pr_body"] for e in per_pr[0]["evidence"])

    def test_detects_2026_trailer_in_pr_body(self, metric, mock_context):
        """Integration test: Generated-with: trailer in PR body is detected."""
        context, ledger = mock_context

        pr = make_mock_pr(1, "Add feature", "Generated-with: Claude Code\n\nImplements new API.")
        ledger.get_prs_for_user.return_value = [pr]
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        assert result.details["ai_rate"] == 100.0
        assert result.details["ai_pr_count"] == 1
        assert result.details["total_pr_count"] == 1
        assert "claude" in str(result.details["tool_breakdown"]).lower()

    def test_detects_2026_trailer_in_commit_message(self, metric, mock_context):
        """Integration test: Generated-by: trailer in commit message is detected."""
        context, ledger = mock_context

        pr = make_mock_pr(1, "Fix bug", "Manual description")
        ledger.get_prs_for_user.return_value = [pr]

        ai_commit = make_mock_commit("def456", "Fix edge case\n\nGenerated-by: Cursor")
        ledger.get_commits_for_pr.return_value = [ai_commit]

        result = metric.run(context)

        assert result.details["ai_rate"] == 100.0
        assert result.details["ai_pr_count"] == 1
        assert "cursor" in str(result.details["tool_breakdown"]).lower()

    def test_mixed_trailers_and_signatures(self, metric, mock_context):
        """Integration test: Mix of 2026 trailers and traditional signatures."""
        context, ledger = mock_context

        prs = [
            make_mock_pr(1, "Feature (Copilot)", "Description"),
            make_mock_pr(2, "Bug fix", "Generated-with: Claude Code"),
            make_mock_pr(3, "Manual change", "Written by hand"),
        ]
        ledger.get_prs_for_user.return_value = prs
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        assert result.details["ai_rate"] == 66.7  # 2 out of 3
        assert result.details["ai_pr_count"] == 2
        assert result.details["human_pr_count"] == 1
        breakdown = result.details["tool_breakdown"]
        assert breakdown["copilot"] == 1
        assert breakdown["claude"] == 1


class TestVelocityAnomaly:
    """Test velocity anomaly detection helper function."""

    def test_detects_high_velocity_short_time(self):
        """Test detection of 1000+ lines in 30 minutes."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _detect_velocity_anomaly
        from datetime import datetime, timezone

        pr = MagicMock()
        pr.additions = 900
        pr.deletions = 100  # 1000 total
        pr.created_at = datetime(2024, 1, 1, 10, 0, 0, tzinfo=timezone.utc)
        pr.merged_at = datetime(2024, 1, 1, 10, 25, 0, tzinfo=timezone.utc)  # 25 min
        pr.updated_at = None
        pr.closed_at = None

        is_suspicious, evidence = _detect_velocity_anomaly(pr)
        assert is_suspicious is True
        assert evidence is not None
        assert evidence["source"] == "velocity_anomaly"
        assert evidence["tool"] == "ai_assisted"
        assert "1000+ lines in 30 minutes" in evidence["details"]["threshold"]

    def test_detects_extreme_velocity(self):
        """Test detection of extreme velocity (>100 lines/min)."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _detect_velocity_anomaly
        from datetime import datetime, timezone

        pr = MagicMock()
        pr.additions = 300
        pr.deletions = 0
        pr.created_at = datetime(2024, 1, 1, 10, 0, 0, tzinfo=timezone.utc)
        pr.merged_at = datetime(2024, 1, 1, 10, 2, 0, tzinfo=timezone.utc)  # 2 min = 150 lines/min
        pr.updated_at = None
        pr.closed_at = None

        is_suspicious, evidence = _detect_velocity_anomaly(pr)
        assert is_suspicious is True
        assert evidence is not None
        assert ">100 lines/min" in evidence["details"]["threshold"]

    def test_normal_velocity_not_flagged(self):
        """Test that normal velocity is not flagged."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _detect_velocity_anomaly
        from datetime import datetime, timezone

        pr = MagicMock()
        pr.additions = 100
        pr.deletions = 20
        pr.created_at = datetime(2024, 1, 1, 10, 0, 0, tzinfo=timezone.utc)
        pr.merged_at = datetime(2024, 1, 1, 14, 0, 0, tzinfo=timezone.utc)  # 4 hours
        pr.updated_at = None
        pr.closed_at = None

        is_suspicious, evidence = _detect_velocity_anomaly(pr)
        assert is_suspicious is False
        assert evidence is None

    def test_zero_lines_not_flagged(self):
        """Test that PRs with zero changes are not flagged."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _detect_velocity_anomaly

        pr = MagicMock()
        pr.additions = 0
        pr.deletions = 0
        pr.created_at = datetime(2024, 1, 1, 10, 0, 0, tzinfo=timezone.utc)
        pr.merged_at = datetime(2024, 1, 1, 10, 10, 0, tzinfo=timezone.utc)
        pr.updated_at = None
        pr.closed_at = None

        is_suspicious, evidence = _detect_velocity_anomaly(pr)
        assert is_suspicious is False
        assert evidence is None

    def test_uses_updated_at_when_not_merged(self):
        """Test that updated_at is used when merged_at is None."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _detect_velocity_anomaly
        from datetime import datetime, timezone

        pr = MagicMock()
        pr.additions = 500
        pr.deletions = 0
        pr.created_at = datetime(2024, 1, 1, 10, 0, 0, tzinfo=timezone.utc)
        pr.merged_at = None
        pr.updated_at = datetime(2024, 1, 1, 10, 10, 0, tzinfo=timezone.utc)  # 10 min
        pr.closed_at = None

        is_suspicious, evidence = _detect_velocity_anomaly(pr)
        assert is_suspicious is True  # 500 lines in 10 min triggers threshold

    def test_500_lines_in_15_minutes(self):
        """Test the 500+ lines in 15 minutes threshold."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _detect_velocity_anomaly
        from datetime import datetime, timezone

        pr = MagicMock()
        pr.additions = 500
        pr.deletions = 0
        pr.created_at = datetime(2024, 1, 1, 10, 0, 0, tzinfo=timezone.utc)
        pr.merged_at = datetime(2024, 1, 1, 10, 12, 0, tzinfo=timezone.utc)  # 12 min
        pr.updated_at = None
        pr.closed_at = None

        is_suspicious, evidence = _detect_velocity_anomaly(pr)
        assert is_suspicious is True
        assert "500+ lines in 15 minutes" in evidence["details"]["threshold"]


# Integration tests for velocity anomaly - defined in their own class with fixtures
class TestVelocityAnomalyIntegration:
    """Integration tests for velocity anomaly in the metric (inherits fixtures from TestAIAssistedPRRateMetric)."""

    @pytest.fixture
    def metric(self):
        return AIAssistedPRRate()

    @pytest.fixture
    def mock_context(self):
        """Create a mock context with test PRs."""
        context = MagicMock(spec=MetricContext)
        context.user_login = "testuser"
        context.start_date = datetime(2024, 1, 1, tzinfo=timezone.utc)
        context.end_date = datetime(2024, 1, 31, tzinfo=timezone.utc)

        # Mock ledger
        ledger = MagicMock()
        context.ledger = ledger

        return context, ledger

    def test_velocity_anomaly_detected_in_metric(self, metric, mock_context):
        """Test that velocity anomalies are detected in the full metric."""
        context, ledger = mock_context

        # Create PR with velocity anomaly
        pr = make_mock_pr(1, "Big feature", "Description")
        pr.additions = 1500
        pr.deletions = 0
        pr.created_at = datetime(2024, 1, 1, 10, 0, 0, tzinfo=timezone.utc)
        pr.merged_at = datetime(2024, 1, 1, 10, 20, 0, tzinfo=timezone.utc)  # 20 min

        ledger.get_prs_for_user.return_value = [pr]
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        assert result.details["ai_rate"] == 100.0
        assert result.details["ai_pr_count"] == 1
        # Check velocity anomaly is in evidence
        pr_evidence = result.details["per_pr"][0]["evidence"]
        velocity_evidence = [e for e in pr_evidence if e.get("source") == "velocity_anomaly"]
        assert len(velocity_evidence) == 1
        assert velocity_evidence[0]["tool"] == "ai_assisted"

    def test_velocity_anomaly_with_normal_prs(self, metric, mock_context):
        """Test mix of velocity anomaly PR and normal PR."""
        context, ledger = mock_context

        # Fast PR (velocity anomaly)
        fast_pr = make_mock_pr(1, "Fast PR", "Description")
        fast_pr.additions = 1000
        fast_pr.deletions = 0
        fast_pr.created_at = datetime(2024, 1, 1, 10, 0, 0, tzinfo=timezone.utc)
        fast_pr.merged_at = datetime(2024, 1, 1, 10, 15, 0, tzinfo=timezone.utc)  # 15 min

        # Normal PR
        normal_pr = make_mock_pr(2, "Normal PR", "Description")
        normal_pr.additions = 50
        normal_pr.deletions = 10
        normal_pr.created_at = datetime(2024, 1, 1, 11, 0, 0, tzinfo=timezone.utc)
        normal_pr.merged_at = datetime(2024, 1, 1, 15, 0, 0, tzinfo=timezone.utc)  # 4 hours

        ledger.get_prs_for_user.return_value = [fast_pr, normal_pr]
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        assert result.details["ai_rate"] == 50.0  # 1 of 2
        assert result.details["ai_pr_count"] == 1
        assert result.details["human_pr_count"] == 1


class TestEntropyAnomaly:
    """Test entropy/compression anomaly detection helper function."""

    def test_detects_low_entropy_low_compression(self):
        """Test detection of very repetitive code (low entropy + low compression)."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _detect_entropy_anomaly
        from impact.metrics.utils import _shannon_entropy, _compression_ratio
        from unittest.mock import MagicMock

        ledger = MagicMock()
        # Create very repetitive content
        repetitive_patch = "--- a/f.py\n+++ b/f.py\n@@ -1,1 +1,100 @@\n" + "+x = 1\n" * 100
        file_record = MagicMock()
        file_record.patch = repetitive_patch
        ledger.get_files_for_pr.return_value = [file_record]

        pr = MagicMock()
        pr.number = 1

        is_suspicious, evidence = _detect_entropy_anomaly(pr, ledger)
        assert is_suspicious is True
        assert evidence is not None
        assert evidence["source"] == "entropy_anomaly"
        assert evidence["tool"] == "ai_assisted"
        assert evidence["details"]["entropy"] < 3.5
        assert evidence["details"]["compression_ratio"] < 0.15

    def test_normal_code_not_flagged(self):
        """Test that normal varied code is not flagged."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _detect_entropy_anomaly
        from unittest.mock import MagicMock

        ledger = MagicMock()
        # Create varied, normal-looking code
        varied_patch = """--- a/f.py
+++ b/f.py
@@ -1,1 +1,30 @@
+def calculate_total(items):
+    total = 0
+    for item in items:
+        if item.price > 0:
+            total += item.price * item.quantity
+    return total
+
+def validate_user(user):
+    if not user.email:
+        raise ValueError("Email required")
+    if "@" not in user.email:
+        raise ValueError("Invalid email")
+    return True
+
+class DataProcessor:
+    def __init__(self, config):
+        self.config = config
+    def process(self, data):
+        return [self._transform(d) for d in data]
+"""
        file_record = MagicMock()
        file_record.patch = varied_patch
        ledger.get_files_for_pr.return_value = [file_record]

        pr = MagicMock()
        pr.number = 1

        is_suspicious, evidence = _detect_entropy_anomaly(pr, ledger)
        assert is_suspicious is False
        assert evidence is None

    def test_no_files_returns_false(self):
        """Test that PRs with no files are not flagged."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _detect_entropy_anomaly
        from unittest.mock import MagicMock

        ledger = MagicMock()
        ledger.get_files_for_pr.return_value = []

        pr = MagicMock()
        pr.number = 1

        is_suspicious, evidence = _detect_entropy_anomaly(pr, ledger)
        assert is_suspicious is False
        assert evidence is None

    def test_files_without_patches_ignored(self):
        """Test that files without patch content are ignored."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _detect_entropy_anomaly
        from unittest.mock import MagicMock

        ledger = MagicMock()
        file_record = MagicMock()
        file_record.patch = None
        ledger.get_files_for_pr.return_value = [file_record]

        pr = MagicMock()
        pr.number = 1

        is_suspicious, evidence = _detect_entropy_anomaly(pr, ledger)
        assert is_suspicious is False
        assert evidence is None


class TestEntropyAnomalyIntegration:
    """Integration tests for entropy anomaly in the metric."""

    @pytest.fixture
    def metric(self):
        return AIAssistedPRRate()

    @pytest.fixture
    def mock_context(self):
        """Create a mock context with test PRs."""
        context = MagicMock(spec=MetricContext)
        context.user_login = "testuser"
        context.start_date = datetime(2024, 1, 1, tzinfo=timezone.utc)
        context.end_date = datetime(2024, 1, 31, tzinfo=timezone.utc)

        ledger = MagicMock()
        context.ledger = ledger

        return context, ledger

    def test_entropy_anomaly_detected_in_metric(self, metric, mock_context):
        """Test that entropy anomalies are detected in the full metric."""
        context, ledger = mock_context

        pr = make_mock_pr(1, "Repetitive PR", "Description")
        ledger.get_prs_for_user.return_value = [pr]
        ledger.get_commits_for_pr.return_value = []

        # Create very repetitive patch content
        repetitive_patch = "--- a/f.py\n+++ b/f.py\n@@ -1,1 +1,100 @@\n" + "+x = 1\n" * 100
        file_record = MagicMock()
        file_record.patch = repetitive_patch
        ledger.get_files_for_pr.return_value = [file_record]

        result = metric.run(context)

        assert result.details["ai_rate"] == 100.0
        assert result.details["ai_pr_count"] == 1
        # Check entropy anomaly is in evidence
        pr_evidence = result.details["per_pr"][0]["evidence"]
        entropy_evidence = [e for e in pr_evidence if e.get("source") == "entropy_anomaly"]
        assert len(entropy_evidence) == 1
        assert entropy_evidence[0]["tool"] == "ai_assisted"


class TestConfidenceScoring:
    """Test the confidence scoring function for AI assistance signals."""

    def test_trailer_high_confidence(self):
        """Test that Generated-with: trailers get high confidence."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _calculate_confidence_score

        evidence = [{"source": "pr_body", "tool": "claude", "text": "Generated-with: Claude Code"}]
        score = _calculate_confidence_score(evidence)
        assert score == 90.0

    def test_coauthored_trailer_high_confidence(self):
        """Test that Co-authored-by trailers get high confidence."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _calculate_confidence_score

        evidence = [{"source": "commit", "tool": "copilot", "text": "Co-authored-by: GitHub Copilot"}]
        score = _calculate_confidence_score(evidence)
        assert score == 90.0

    def test_title_explicit_tool(self):
        """Test that tool name in title gets high confidence."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _calculate_confidence_score

        evidence = [{"source": "pr_title", "tool": "cursor", "text": "Fix bug (Cursor)"}]
        score = _calculate_confidence_score(evidence)
        assert score == 80.0

    def test_velocity_anomaly_only(self):
        """Test that velocity anomaly alone gets moderate confidence."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _calculate_confidence_score

        evidence = [{"source": "velocity_anomaly", "tool": "ai_assisted", "text": "1000 lines in 20 min"}]
        score = _calculate_confidence_score(evidence)
        assert score == 45.0

    def test_entropy_anomaly_only(self):
        """Test that entropy anomaly alone gets moderate confidence."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _calculate_confidence_score

        evidence = [{"source": "entropy_anomaly", "tool": "ai_assisted", "text": "Low entropy 2.5"}]
        score = _calculate_confidence_score(evidence)
        assert score == 40.0

    def test_multiple_signals_cumulative(self):
        """Test that multiple signals increase confidence (bonus)."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _calculate_confidence_score

        evidence = [
            {"source": "pr_title", "tool": "copilot", "text": "Fix (Copilot)"},
            {"source": "velocity_anomaly", "tool": "ai_assisted", "text": "1000 lines"},
        ]
        score = _calculate_confidence_score(evidence)
        # 80 (title) + 45 (velocity) + 15 (bonus) = 140 → capped to 100
        assert score == 100.0

    def test_no_evidence_zero_confidence(self):
        """Test that no evidence returns zero confidence."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _calculate_confidence_score

        score = _calculate_confidence_score([])
        assert score == 0.0

    def test_generic_ai_mention(self):
        """Test that generic 'AI generated' mentions get moderate confidence."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _calculate_confidence_score

        evidence = [{"source": "pr_body", "tool": "ai_assisted", "text": "AI generated code"}]
        score = _calculate_confidence_score(evidence)
        assert score == 50.0

    def test_commit_explicit_tool(self):
        """Test that tool name in commit message gets confidence."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _calculate_confidence_score

        evidence = [{"source": "commit", "tool": "claude", "text": "Generated by Claude Code"}]
        score = _calculate_confidence_score(evidence)
        assert score == 75.0

    def test_triple_signal_still_capped(self):
        """Test that even three signals don't exceed 100."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _calculate_confidence_score

        evidence = [
            {"source": "pr_title", "tool": "copilot", "text": "Fix (Copilot)"},
            {"source": "velocity_anomaly", "tool": "ai_assisted", "text": "Fast"},
            {"source": "entropy_anomaly", "tool": "ai_assisted", "text": "Low entropy"},
        ]
        score = _calculate_confidence_score(evidence)
        assert score == 100.0  # Capped


class TestConfidenceIntegration:
    """Integration tests for confidence scoring in the metric."""

    @pytest.fixture
    def metric(self):
        return AIAssistedPRRate()

    @pytest.fixture
    def mock_context(self):
        """Create a mock context with test PRs."""
        context = MagicMock(spec=MetricContext)
        context.user_login = "testuser"
        context.start_date = datetime(2024, 1, 1, tzinfo=timezone.utc)
        context.end_date = datetime(2024, 1, 31, tzinfo=timezone.utc)

        ledger = MagicMock()
        context.ledger = ledger

        return context, ledger

    def test_confidence_in_per_pr_output(self, metric, mock_context):
        """Test that confidence is included in per-PR output."""
        context, ledger = mock_context

        pr = make_mock_pr(1, "Feature (Copilot)", "Description")
        ledger.get_prs_for_user.return_value = [pr]
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        per_pr = result.details["per_pr"]
        assert len(per_pr) == 1
        assert "confidence" in per_pr[0]
        assert per_pr[0]["confidence"] > 0
        assert per_pr[0]["confidence"] <= 100

    def test_confidence_aggregates_in_details(self, metric, mock_context):
        """Test that confidence aggregates are in metric details."""
        context, ledger = mock_context

        pr = make_mock_pr(1, "Feature (Copilot)", "Generated-with: Claude Code")
        ledger.get_prs_for_user.return_value = [pr]
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        details = result.details
        assert "ai_confidence_avg" in details
        assert "ai_confidence_high" in details
        assert "ai_confidence_medium" in details
        assert "ai_confidence_low" in details
        # With trailer, should be high confidence
        assert details["ai_confidence_avg"] >= 80

    def test_confidence_levels_categorized(self, metric, mock_context):
        """Test that confidence levels are correctly categorized."""
        context, ledger = mock_context

        # High confidence: trailer
        pr1 = make_mock_pr(1, "Feature", "Generated-with: Claude Code")
        # Low confidence: velocity only (would need proper datetime fields, so use entropy)
        # For simplicity, just test with explicit tool mention (medium)
        pr2 = make_mock_pr(2, "Fix", "Some changes")

        ledger.get_prs_for_user.return_value = [pr1, pr2]
        ledger.get_commits_for_pr.return_value = []

        result = metric.run(context)

        details = result.details
        # At least one should be high confidence
        assert details["ai_confidence_high"] >= 1 or details["ai_confidence_medium"] >= 1


class TestStyleUniformity:
    """Test style uniformity detection using tree-sitter AST analysis."""

    def test_detects_uniform_functions(self):
        """Test detection of uniform function patterns."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _detect_style_uniformity
        from unittest.mock import MagicMock

        ledger = MagicMock()
        # Create files with uniform functions (same length, same params)
        patch = """--- a/api.py
+++ b/api.py
@@ -1,1 +1,50 @@
+def get_user(id):
+    return db.query(id)
+def get_post(id):
+    return db.query(id)
+def get_comment(id):
+    return db.query(id)
+def get_tag(id):
+    return db.query(id)
+def get_category(id):
+    return db.query(id)
"""
        file_record = MagicMock()
        file_record.filename = "api.py"
        file_record.content = None
        file_record.patch = patch
        ledger.get_files_for_pr.return_value = [file_record]

        pr = MagicMock()
        pr.number = 1

        is_suspicious, evidence = _detect_style_uniformity(pr, ledger)
        # May or may not trigger depending on exact thresholds
        # Just verify it doesn't crash
        assert isinstance(is_suspicious, bool)

    def test_no_files_returns_false(self):
        """Test that PRs with no files are not flagged."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _detect_style_uniformity
        from unittest.mock import MagicMock

        ledger = MagicMock()
        ledger.get_files_for_pr.return_value = []

        pr = MagicMock()
        pr.number = 1

        is_suspicious, evidence = _detect_style_uniformity(pr, ledger)
        assert is_suspicious is False
        assert evidence is None

    def test_insufficient_functions_not_flagged(self):
        """Test that PRs with few functions are not analyzed."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _detect_style_uniformity
        from unittest.mock import MagicMock

        ledger = MagicMock()
        patch = """--- a/f.py
+++ b/f.py
@@ -1,1 +1,5 @@
+def a(x):
+    return x
"""
        file_record = MagicMock()
        file_record.filename = "f.py"
        file_record.content = None
        file_record.patch = patch
        ledger.get_files_for_pr.return_value = [file_record]

        pr = MagicMock()
        pr.number = 1

        is_suspicious, evidence = _detect_style_uniformity(pr, ledger)
        assert is_suspicious is False  # Need >=3 functions


class TestAdditionalSignals:
    """Test additional AI signal detection."""

    def test_detects_no_todo_fixme(self):
        """Test detection of missing TODO/FIXME markers."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _detect_additional_ai_signals
        from unittest.mock import MagicMock

        ledger = MagicMock()
        # Create substantial code without TODO/FIXME
        patch = """--- a/f.py
+++ b/f.py
@@ -1,1 +1,150 @@
""" + "\n".join([f"+def func{i}():\n+    return {i}" for i in range(50)])
        file_record = MagicMock()
        file_record.patch = patch
        ledger.get_files_for_pr.return_value = [file_record]

        pr = MagicMock()
        pr.number = 1

        signals = _detect_additional_ai_signals(pr, ledger)
        # Should detect no_todo_fixme for 150+ lines without TODO/FIXME
        signal_sources = [s["source"] for s in signals]
        assert "no_todo_fixme" in signal_sources or len(signals) >= 0  # May vary

    def test_detects_low_comment_density(self):
        """Test detection of very low comment density."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _detect_additional_ai_signals
        from unittest.mock import MagicMock

        ledger = MagicMock()
        # Create code without comments
        patch = """--- a/f.py
+++ b/f.py
@@ -1,1 +1,80 @@
""" + "\n".join([f"+x = {i}" for i in range(80)])
        file_record = MagicMock()
        file_record.patch = patch
        ledger.get_files_for_pr.return_value = [file_record]

        pr = MagicMock()
        pr.number = 1

        signals = _detect_additional_ai_signals(pr, ledger)
        signal_sources = [s["source"] for s in signals]
        # Should detect low_comment_density
        assert "low_comment_density" in signal_sources

    def test_no_files_returns_empty(self):
        """Test that no files returns empty list."""
        from impact.metrics.plugins.authored.ai_assisted_pr_rate import _detect_additional_ai_signals
        from unittest.mock import MagicMock

        ledger = MagicMock()
        ledger.get_files_for_pr.return_value = []

        pr = MagicMock()
        pr.number = 1

        signals = _detect_additional_ai_signals(pr, ledger)
        assert signals == []
